# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='river',
            name='section',
            field=models.CharField(default=' ', max_length=250),
        ),
    ]
