# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('rivers', '0002_river_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='river',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.State'),
        ),
    ]
