# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-14 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivers', '0005_river_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='river',
            name='image',
            field=models.ImageField(default='/img/rapids.jpg', upload_to='static/img'),
        ),
    ]
