# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 21:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rivers', '0002_river_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiverSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_level', models.FloatField()),
                ('river', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rivers.River')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
